# Site
name: 'TEE.Lab'
description: 'Homepage of Theoretical Evolutionary Ecology Lab at the University of Lausanne'
logo: 'assets/images/front.jpg'
favicon: 'assets/images/favicon.ico'

include: ["_pages"]
#permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  
authors:
    charles:
      name:           Charles Mullon
      title:          Head, PI
      site:           
      avatar:         charles.jpg
      bio:            "After undergraduate studies in Mathematics, Charles did his PhD in evolutionary biology on the evolution of sexual dimorphism at University College London. He then moved to the University of Lausanne for a post-doc investigating the emergence of social polymorphism in structured populations. He then went to Japan for a brief time as an invited lecturer. Starting January 2020, he is an Eccellenza assistant professor at the University of Lausanne."
      email:          charles.mullon@unil.ch
      twitter:        https://twitter.com/MullonDlm
      github:         
      googlescholar:  https://scholar.google.ch/citations?user=3m8FuuMAAAAJ
      researchgate:   https://www.researchgate.net/profile/Charles-Mullon
      orcid:          https://orcid.org/0000-0002-9875-4227
  
    thomas:
      name:           Thomas Lesaffre
      title:          Post-doc
      site:           
      avatar:         thomas.jpg
      bio:            "Thomas obtained his Master's degree in evolutionary ecology at the University of Lille (France), followed by a PhD in theoretical population genetics with Sylvain Billiard in the same institution. During his PhD, he used both analytical and individual-centered simulation approaches to study the link between perenniality, inbreeding depression and mating systems in flowering plants. After defending his thesis in March 2021, he joined the lab in October 2021 as a post-doc to continue to develop theory on plant evolution by trying to better incorporate plant physiological processes into evolutionary theory."
      email:          thomas.lesaffre@unil.ch
      twitter:        https://twitter.com/Thomas_Lsffr
      github:         
      googlescholar:  https://scholar.google.fr/citations?user=ENCt7ScAAAAJ
      researchgate:   https://www.researchgate.net/profile/Thomas-Lesaffre
      orcid:          hhttps://orcid.org/0000-0002-0815-259X
 
    ewan:
      name:           Ewan Flintham
      title:          Post-doc
      site:           
      avatar:         ewan.png
      bio:            "Ewan completed an undergraduate degree in Biology at the University of Oxford before moving to Imperial College London to do a master's in Computational Biology and a PhD in theoretical evolutionary biology supervised by Vincent Savolainen and Charles Mullon. He joined the lab full-time in Autumn 2022 as a post-doc. Ewan uses mathematical models and computer simulations to study eco-evolutionary dynamics in sexual systems. In particular, he is interested in the role of population ecology in driving the evolution of sexual reproduction and biological sex differences."
      email:          e.flintham17@imperial.ac.uk
      twitter:        https://twitter.com/EwanFlintham
      github:         
      googlescholar:  https://scholar.google.com/citations?user=IRxOMq4AAAAJ
      researchgate:   
      orcid:         
   
    iris:
      name:           Iris Prigent
      title:          PhD student
      site:           
      avatar:         iris.jpg
      bio:            "Iris holds a Msc in evolutionary biology from the Université de Montpellier with a background in mathematics. She previously worked with Fabien Condamine (Institut des Sciences de l’Evolution de Montpellier) on the phylogeny of cycads, and with Amaury Lambert and Julie Marin (College de France) on modelling the effect of gene flow on gene trees. Iris is now a PhD student modelling evolution in metapopulations. Using mathematical modelling, she wants to understand the emergence of polymorphism for functional traits that influence a species’ ecology with long term effects, such as resource use strategies or habitat maintenance."
      email:          iris.prigent@unil.ch
      twitter:        https://twitter.com/iris_prigent
      github:         https://github.com/iris-prigent
      googlescholar:  
      researchgate:   
      orcid:          
 
    vitor:
      name:           Vitor Sudbrack
      title:          PhD student
      site:           http://sudbrack.me
      avatar:         vitor.jpg
      bio:            "Coming from physics, Vitor's Master thesis with Roberto Kraenkel at the Institute for Theoretical Physics (IFT/Unesp, Brazil) focused on modeling the effects of habitat fragmentation into single species dynamics in artificial landscapes. During a scientific stay at the Institute for Interdisciplinary Physics and Complex Systems (IFISC/CSIC/UiB, Spain), Vitor studied competition release between two competing species in fragmented landscapes. In his PhD, he will investigate the effects of population structure on the segregation of social and competitive alleles to better understand the pace and underlying genetic signatures of adaptation in non-randomly mixing populations."
      email:          vitor.sudbrack@unil.ch
      twitter:        https://twitter.com/vitorsudbrack
      github:         https://github.com/vsudbrack
      googlescholar:  https://scholar.google.com/citations?user=fQ4x-1LZ-nEC
      researchgate:   https://www.researchgate.net/profile/Vitor-Sudbrack
      orcid:          https://orcid.org/0000-0002-4815-2092

alumni:  
    franz:
      name:           Franz Chai
      title:          Master student
      site:           
      avatar:         franz.jpeg
      bio:            "Franz worked on the project <i>The effect of encounter rate on sexual discrimination</i> under the supervision of Ewan."
      email:          franz.chai@unil.ch
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid:          

    max:
      name:           Max Schmid
      title:          Post-doc
      site:           https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/biologie/institute/evolution-und-oekologie/lehrbereiche/vegetationsoekologie/mitarbeiterinnen/dr-max-schmid/
      avatar:         max.jpg
      bio:            "After a post-doc in our lab, Max is now an Assistant Professor at the University of Tübingen, Germany."
      email:          max.schmid@uni-tuebingen.de
      twitter:        https://twitter.com/max_schmid_
      github:         
      googlescholar:  https://scholar.google.ch/citations?user=GLNBMysAAAAJ&oi=ao
      researchgate:   https://www.researchgate.net/profile/Max-Schmid-2
      orcid:          https://orcid.org/0000-0001-7197-4775

    marco:
      name:           Marco Fele
      title:          Master student
      site:           
      avatar:         marco.jpg
      bio:            "After investigating whether leadership favors colony performance in the decision-making process with simulations, Marco is currently a PhD student at Swansea University, UK."
      email:          
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 

    manuel:
      name:           Manuel Grubb
      title:          Master student
      site:           
      avatar:         no.jpg
      bio:            "Manuel developed the project <i>The effect of ecological inheritance on the evolution of resource consumption</i> under the supervision of Iris."
      email:           
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 
      
    loraine:
      name:           Loraine Hablützel
      title:          Master student
      site:           https://banklab.github.io/people/
      avatar:         loraine.jpeg
      bio:            "After her Master project supervised by Max, Loraine is now a PhD student at the University of Bern. "
      email:          loraine.habluetzel@unibe.ch
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 

    marie:
      name:           Marie Kolsh
      title:          Master student
      site:           
      avatar:         marie.png
      bio:            "Marie studied the effects of social structure and dispersion on the culture of vervet monkeys, supervised by Charles Mullon and Erica van de Waal."
      email:           
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 
      


collections:
  projects:
    output: true
    title: List of Projects
    directory: ./_projects
  courses:
    output: true
    title: List of Courses
    directory: ./_courses


# Syntax
markdown: kramdown
highlighter: rouge

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
