# Site
name: 'TEE.Lab'
title: 'TEE.Lab'
description: 'Homepage of Theoretical Evolutionary Ecology Lab at the University of Lausanne'
logo: 'assets/images/front.jpg'
favicon: 'assets/images/favicon.ico'

include: ["_pages"]
#permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  
authors:
    charles:
      name:           Charles Mullon
      title:          Head, PI
      site:           
      avatar:         charles.jpg
      bio:            "After completing an undergraduate degree in Mathematics, Charles obtained a PhD in evolutionary biology at University College London, looking at the evolution of sexual dimorphism. He then moved to the University of Lausanne for a postdoctoral position investigating the evolution of social polymorphism. Following a brief period in Japan as a lecturer, he returned to Lausanne in January 2020 to establish a research group as an Eccellenza Group Leader. Since 2024, he has been a professor of evolutionary ecology."
      email:          charles.mullon@unil.ch
      github:         
      researchgate:   https://www.researchgate.net/profile/Charles-Mullon
      orcid:          https://orcid.org/0000-0002-9875-4227
      bluesky:        "charlesmullon.bsky.social"
  
    thomas:
      name:           Thomas Lesaffre
      title:          Post-doc
      site:           
      avatar:         thomas.jpeg
      bio:            "Thomas obtained his Master's degree in evolutionary ecology at the University of Lille (France), followed by a PhD in theoretical population genetics with Sylvain Billiard in the same institution. During his PhD, he used mathematical models and individual-centred simulations to study the link between life-history, mating system and mutation load in flowering plants. After defending his thesis in March 2021, he joined the lab in October 2021 as a post-doc. He currently works on the evolution of plant sexual systems, with a particular focus on the transition from hermaphroditism, where individuals express male and female sexual functions, to dioecy, where individuals are unisexual."
      email:          thomas.lesaffre@unil.ch
      site:           https://thomas-lesaffre.github.io/
 
    ewan:
      name:           Ewan Flintham
      title:          Post-doc
      site:           
      avatar:         ewan.png
      bio:            "Ewan completed an undergraduate degree in Biology at the University of Oxford before moving to Imperial College London to do a Master's in Computational Biology and a PhD in theoretical evolutionary biology supervised by Vincent Savolainen and Charles Mullon. He joined the lab full-time in Autumn 2022 as a post-doc. Ewan uses mathematical models and computer simulations to study eco-evolutionary dynamics in sexual systems. In particular, he is interested in the ecological drivers of selection in males and females, and the consequence of this for demography and patterns of genetic variation."
      email:          ewan.flintham@unil.ch
      twitter:        https://twitter.com/EwanFlintham
      github:         
      googlescholar:  https://scholar.google.com/citations?user=IRxOMq4AAAAJ
      researchgate:   
      orcid:         
   
    miguel:
      name:           Miguel dos Santos
      title:          Post-doc
      site:           
      avatar:         miguel.jpg
      bio:            "Miguel obtained both his master and PhD in evolutionary biology at the University of Lausanne with Claus Wedekind, investigating the evolution of punishment to promote cooperation in humans. He then joined Stu West’s group at the University of Oxford to focus on social evolution theory. After a postdoc on cooperation and punishment in social psychology with Daria Knoch at the University of Bern, he worked again for Stu West in Oxford, to study the evolution of social behaviours in variable environments. He then joined Charles Mullon’s lab in September 2024. Using theory, he now investigates how the intergenerational effects of reputation shape cooperation in social dilemmas."
      email:          miguel.dossantos@unil.ch
      twitter:        https://twitter.com/Mig_mds
      github:         
      googlescholar:  https://scholar.google.ch/citations?user=HVDBogwAAAAJ
      researchgate:   
      orcid:  
      bluesky:        "drmigo.bsky.social"

    malvika:
      name:           Malvika Srivastava
      title:          Post-doc
      site:           
      avatar:         malvika.jpg
      bio:            "Malvika completed her B.Sc. in physics from St. Stephen’s college, Delhi and then moved to Cologne to pursue her M.Sc. with a specialisation in statistical and biological physics. During her masters research, she worked on a geometric classification of fitness landscapes and studied its implications for the evolution of recombination. She continued working on fitness landscapes across multiple scales for her Ph.D. at ETH Zurich, where her research ranged from the level of transcription factor-DNA interactions to the level of body-plan development. After defending her PhD in August 2024, she joined the TEE group from October 2024 as a post-doc, where she is excited to integrate ecological interactions in her research."
      email:          malvika.srivastava@unil.ch
      twitter:        https://x.com/M_Srivastava_
      github:         
      googlescholar:  https://scholar.google.com/citations?user=g6eLK2IAAAAJ
      researchgate:   
      orcid:          https://orcid.org/0000-0003-0757-4990


    iris:
      name:           Iris Prigent
      title:          PhD student
      site:           
      avatar:         iris.jpg
      bio:            "Iris holds a Msc in evolutionary biology from the Université de Montpellier with a background in mathematics. She previously worked with Fabien Condamine (Institut des Sciences de l’Evolution de Montpellier) on the phylogeny of cycads, and with Amaury Lambert and Julie Marin (College de France) on modelling the effect of gene flow on gene trees. Iris is now a PhD student modelling evolution in metapopulations. Using mathematical modelling, she wants to understand the emergence of polymorphism for functional traits that influence a species’ ecology with long term effects, such as resource use strategies or habitat maintenance."
      email:          iris.prigent@unil.ch
      twitter:        https://twitter.com/iris_prigent
      github:         https://github.com/iris-prigent
      googlescholar:  
      researchgate:   
      orcid:          
 
    vitor:
      name:           Vitor Sudbrack
      title:          PhD student
      site:           http://sudbrack.me
      avatar:         vitor.jpg
      bio:            "Coming from physics, Vitor's Master's thesis with Roberto Kraenkel at the Institute for Theoretical Physics (IFT/Unesp, Brazil) focused on modeling the effects of habitat fragmentation into single species dynamics in artificial landscapes. During a scientific stay at the Institute for Interdisciplinary Physics and Complex Systems (IFISC/CSIC/UiB, Spain), Vitor studied competition release between two competing species in fragmented landscapes. In his PhD, he will investigate the effects of population structure on the segregation of social and competitive alleles to better understand the pace and underlying genetic signatures of adaptation in non-randomly mixing populations."
      email:          vitor.sudbrack@unil.ch
      twitter:        https://twitter.com/vitorsudbrack
      github:         https://github.com/vsudbrack
      googlescholar:  https://scholar.google.com/citations?user=fQ4x-1LZ-nEC
      researchgate:   https://www.researchgate.net/profile/Vitor-Sudbrack
      orcid:          https://orcid.org/0000-0002-4815-2092

    ritam:
      name:           Ritam Das
      title:          PhD student
      avatar:         ritam.jpg
      bio:            "Ritam completed his BS-MS in Physics at the Indian Institute of Science Education and Research Mohali. For his Master’s thesis, he worked in the CoCoMo Group at the Max Planck Institute of Animal Behaviour in Konstanz, where he developed an event detector for animal calls using machine learning techniques. In September 2024, he joined the TEE Lab as a PhD student."
      email:          ritam.das@unil.ch
      twitter: https://x.com/_ritamdas

    julie:
      name:           Julie Roux
      title:          PhD student
      avatar:         julie.jpg
      bio:            "Julie completed her Master’s degree in Evolutionary Biology at the Université de Montpellier. During her Master’s studies, she developed an eco-evolutionary model for gynodioecious species under the supervision of Patrice David (Centre d'Écologie Fonctionnelle et Évolutive, Montpellier). She also conducted a meta-analysis on the strength of sexual selection on song diversity in Oscines, supervised by Erwan Harscouët and Claire Doutrelant (CEFE, Montpellier). In December 2024, she joined the TEE as a PhD student. Her PhD research focuses on developing a sexual selection model to study the joint dynamics of condition and condition-dependent traits."
      email:          julie.roux@unil.ch

    ayoub:
      name:           Ayoub Hartaoui
      title:          Master's student
      site:           
      avatar:         ayoub.jpg
      bio:            "Ayoub Hartaoui obtained his Bachelor's degree in biology from the University of Neuchâtel with a <i>cum laude</i> distinction. He is currently a Master's student in the specialization Computational Ecology and Evolution of the Behaviour, Evolution and Conservation (BEC) program at the University of Lausanne. In the lab, he works with Miguel to investigate the evolution of intergroup cooperation and conflict using agent-based models grounded in climate variability and trait diversity."
      email:           ayoub.hartaoui@unil.ch
      twitter:        
      github:         https://github.com/ayoubhartaoui
      googlescholar:  
      researchgate:   
      orcid: 
    
    alexis:
      name:           Alexis Fornallaz
      title:          Master's student
      site:           
      avatar:         alexis.png
      bio:            "Alexis is a Master’s student in the BEC (Behaviour, Evolution and Conservation) program at the University of Lausanne. He is working with Malvika on a project modelling caste antagonism in ants. He holds a Bachelor’s degree in Biology from UNIL."
      email:           alexis.fornallaz@unil.ch
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 


        
alumni:  
    franz:
      name:           Franz Chai
      title:          Master's student
      site:           
      avatar:         franz.jpeg
      bio:            "Franz worked on the project <i>The effect of encounter rate on sexual discrimination</i> under the supervision of Ewan."
      email:          franz.chai@unil.ch
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid:          

    max:
      name:           Max Schmid
      title:          Post-doc
      site:           https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/biologie/institute/evolution-und-oekologie/lehrbereiche/vegetationsoekologie/mitarbeiterinnen/dr-max-schmid/
      avatar:         max.jpg
      bio:            "After a post-doc in our lab, Max is now an Assistant Professor at the University of Tübingen, Germany."
      email:          max.schmid@uni-tuebingen.de
      twitter:        https://twitter.com/max_schmid_
      github:         
      googlescholar:  https://scholar.google.ch/citations?user=GLNBMysAAAAJ&oi=ao
      researchgate:   https://www.researchgate.net/profile/Max-Schmid-2
      orcid:          https://orcid.org/0000-0001-7197-4775

    marco:
      name:           Marco Fele
      title:          Master's student
      site:           
      avatar:         marco.jpg
      bio:            "After investigating whether leadership favors colony performance in the decision-making process with simulations, Marco is currently a PhD student at Swansea University, UK."
      email:          
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 

    manuel:
      name:           Manuel Grubb
      title:          Master's student
      site:           
      avatar:         no.jpg
      bio:            "Manuel developed the project <i>The effect of ecological inheritance on the evolution of resource consumption</i> under the supervision of Iris."
      email:           
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 
      
    loraine:
      name:           Loraine Hablützel
      title:          Master's student
      site:           https://banklab.github.io/people/
      avatar:         loraine.jpeg
      bio:            "After her Master's project supervised by Max, Loraine is now a PhD student at the University of Bern."
      email:          loraine.habluetzel@unibe.ch
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 

    marie:
      name:           Marie Kolsh
      title:          Master's student
      site:           
      avatar:         marie.png
      bio:            "Marie studied the effects of social structure and dispersion on the culture of vervet monkeys, supervised by Charles Mullon and Erica van de Waal."
      email:           
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 
      


collections:
  projects:
    output: true
    title: List of Projects
    directory: ./_projects
  courses:
    output: true
    title: List of Courses
    directory: ./_courses


# Syntax
markdown: kramdown
highlighter: rouge

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
