# Site
name: 'TEE.Lab'
description: 'Homepage of Theoretical Evolutionary Ecology Lab at the University of Lausanne'
logo: 'assets/images/front.jpg'
favicon: 'assets/images/favicon.ico'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    charles:
      name:           Charles Mullon
      title:          Head, PI
      site:           
      avatar:         charles.jpg
      bio:            "After completing undergraduate studies in Mathematics, Charles did his PhD in evolutionary biology with Max Reuter and Andrew Pomiankowski on the evolution of sexual dimorphism at University College London. He then moved to the University of Lausanne for a post-doc with Laurent Lehmann and Laurent Keller investigating the emergence of social polymorphism in spatially structured populations. He then went to Japan for a brief time as an assistant professor. Starting January 2020, he is an Eccellenza assistant professor at the University of Lausanne."
      email:          charles.mullon@unil.ch
      twitter:        https://twitter.com/MullonDlm
      github:         
      googlescholar:  https://scholar.google.ch/citations?user=3m8FuuMAAAAJ
      researchgate:   https://www.researchgate.net/profile/Charles-Mullon
      orcid:          https://orcid.org/0000-0002-9875-4227
 
    max:
      name:           Max Schmid
      title:          Post-doc
      site:           
      avatar:         max.jpg
      bio:            "Max obtained his Master’s degree in environmental sciences at ETH Zurich, followed by a PhD in evolutionary biology with Frédéric Guillaume at the University of Zurich. In his PhD, Max used individual-based simulations and mathematical models to study local adaptation, evolution during range dynamics, and evolutionary rescue from environmental change. After two subsequent post-doc projects with Felix Gugerli (WSL) and Christoph Zollikofer (UZH), Max joined the lab as a post-doc in autumn 2020. He will study the evolution of the genetic architecture of social traits in spatially-structured populations."
      email:          max.schmid@unil.ch
      twitter:        https://twitter.com/max_schmid_
      github:         
      googlescholar:  https://scholar.google.ch/citations?user=GLNBMysAAAAJ&oi=ao
      researchgate:   https://www.researchgate.net/profile/Max-Schmid-2
      orcid:          https://orcid.org/0000-0001-7197-4775
 
    iris:
      name:           Iris Prigent
      title:          PhD student
      site:           
      avatar:         iris.jpg
      bio:            "Iris holds a Msc in evolutionary biology from the Université de Montpellier with a background in mathematics. She previously worked with Fabien Condamine (Institut des Sciences de l’Evolution de Montpellier) on the phylogeny of cycads, and with Amaury Lambert and Julie Marin (College de France) on modelling the effect of gene flow on gene trees. Iris is now a PhD student modelling evolution in metapopulations. Using mathematical modelling, she wants to understand the emergence of polymorphism for functional traits that influence a species’ ecology with long term effects, such as resource use strategies or habitat maintenance."
      email:          iris.prigent@unil.ch
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid:          
 
 
    vitor:
      name:           Vitor Sudbrack
      title:          PhD student
      site:           https://vsudbrack.github.io/
      avatar:         vitor.jpg
      bio:            "Coming from physics, Vitor's Master thesis with Roberto Kraenkel at the Institute for Theoretical Physics (IFT/Unesp, Brazil) focused on modeling the effects of habitat fragmentation into single species dynamics in artificial landscapes. During a scientific stay at the Institute for Interdisciplinary Physics and Complex Systems (IFISC/CSIC/UiB, Spain), Vitor studied competition release between two competing species in fragmented landscapes. In his PhD, he will investigate the effects of population structure on the segregation of social and competitive alleles to better understand the pace and underlying genetic signatures of adaptation in non-randomly mixing populations."
      email:          vitor.sudbrack@unil.ch
      twitter:        https://twitter.com/vitorsudbrack
      github:         https://github.com/vsudbrack
      googlescholar:  https://scholar.google.com/citations?user=fQ4x-1LZ-nEC
      researchgate:   https://www.researchgate.net/profile/Vitor-Sudbrack
      orcid:          https://orcid.org/0000-0002-4815-2092

    ewan:
      name:           Ewan Flintham
      title:          PhD student
      site:           
      avatar:         ewan.png
      bio:            "Ewan completed an undergraduate degree in Biology at the University of Oxford and a master's in Computational Biology at Imperial College London. He is currently a PhD student at Imperial supervised by Vincent Savolainen, Matteo Fumagalli and Charles Mullon. He uses mathematical models to study the evolutionary genetics of sex-specific selection and sexual conflict. In particular, he is interested in the role of population ecology in influencing the evolution of sex differences, and the repercussions of this for patterns of genetic variation in natural populations."
      email:          e.flintham17@imperial.ac.uk
      twitter:        https://twitter.com/EwanFlintham
      github:         
      googlescholar:  https://scholar.google.com/citations?user=IRxOMq4AAAAJ
      researchgate:   
      orcid:         

    loraine:
      name:           Loraine Hablützel
      title:          Master student
      site:           
      avatar:         loraine.jpeg
      bio:            "I initially took a more classical approach to biology by majoring in Plant and Animal Sciences during my bachelors at Uni Basel. Now enrolled in the Master program BEC at UniL, I am interested in exploring the more theoretical aspects of studying ecology. My Master project is on local adaptation and the effects of different life history strategies. The project involves simulations in Nemo and potentially setting up a mathematical model. It is supervised by Max."
      email:          loraine.hablutzel@unil.ch 
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 

    marie:
      name:           Marie Kolsh
      title:          Master student
      site:           
      avatar:         no.jpg
      bio:            ""
      email:          marie.kolsh@unil.ch 
      twitter:        
      github:         
      googlescholar:  
      researchgate:   
      orcid: 
      
papers:
    charles2021b:
      year: 2021
      authors: <b>Mullon, C.</b>, Wakano, JY., Ohtsuki, H.
      title: Coevolutionary dynamics of genetic traits and their long-term extended effects under non-random interactions
      journal: Jsournal of Theoretical Biology
      url: https://www.sciencedirect.com/science/article/pii/S0022519321001727
    charles2021a:
      year: 2021 
      authors: <b>Flintham, EO.</b>, Savolainen, V., <b>Mullon, C.</b>
      title: Dispersal alters the nature and scope of sexually antagonistic variation
      journal: The American Naturalist 
      url: https://www.journals.uchicago.edu/doi/abs/10.1086/713739?journalCode=an
    charles2021:
      year: 2021
      authors: Weyna A., Romiguier J., <b>Mullon, C.</b>
      title: Hybridization enables the fixation of selfish queen genotypes in eusocial colonies
      journal: BioRxiv (preprint)
      url: https://www.biorxiv.org/content/biorxiv/early/2021/02/02/2021.01.12.426359.full.pdf
    charles2020e:
      year: 2020 
      authors: <b>Mullon, C.</b>
      title: Evolutionary insights into disassortative mating and its association to an ecologically relevant supergene
      journal: Peer Community in Evolutionary Biology
      url: https://hal.archives-ouvertes.fr/hal-02950549/document
    charles2020c:
      year: 2020 
      authors: Roux, C., <b>Mullon, C.</b>, Neuenschwander, S., Pannell, J R. 
      title: Sex allocation, inbreeding, and measures of population differentiation in hermaphroditic metapopulations
      journal: BioRxiv (preprint)
      url: https://www.biorxiv.org/content/10.1101/2020.05.08.080929v1.abstract
    charles2019:
      year: 2019
      authors: <b>Mullon, C.</b> & Lehmann, L. 
      title: An evolutionary quantitative genetics model for phenotypic (co)variance under limited dispersal, with an application to socially synergistic traits
      journal: Evolution
      url: https://onlinelibrary.wiley.com/doi/full/10.1111/evo.13803
    charles2018d:
      year: 2018 
      authors: <b>Mullon, C.</b> & Lehmann, L. 
      title: Eco-evolutionary dynamics in metacommunities&#58 ecological inheritance, helping within- and harming between-species
      journal: The American Naturalist
      url: https://www.journals.uchicago.edu/doi/abs/10.1086/700094
    charles2018c:
      year: 2018 
      authors: <b>Mullon, C.</b>, Keller, L., Lehmann, L. 
      title: Social polymorphism is favoured by the co-evolution of dispersal with social behaviour
      journal: Nature Ecology and Evolution
      url: https://www.nature.com/articles/s41559-017-0397-y
    charles2018b:
      year: 2018 
      authors: Richardson, T., <b>Mullon, C.</b>, Marshall, J., Franks, N., Schlegel, T. 
      title: The influence of the few&#58 a stable ‘oligarchy’ controls information flow in house-hunting ants
      journal: Proceedings B
      url: http://rspb.royalsocietypublishing.org/content/285/1872/20172726
    charles2018a:
      year: 2018 
      authors: Mullon, Chr. & <b>Mullon, C</b>.
      title: A constraint-based framework to study competition and cooperation in fishing
      journal: Fisheries Research
      url: http://www.sciencedirect.com/science/article/pii/S0165783617302187
    charles2017:
      year: 2017 
      authors: <b>Mullon, C.</b> & Lehmann, L.
      title: Invasion fitness for gene-culture co-evolution in family-structured populations with an application to cumulative culture under vertical transmission
      journal: Theoretical Population Biology
      url: http://www.sciencedirect.com/science/article/pii/S0040580917300096
    charles2016b:
      year: 2016
      authors: Lehmann, L., <b>Mullon, C.</b>, Akçay, E., Van Cleve, J.
      title: Invasion fitness, inclusive fitness, and reproductive numbers in heterogeneous populations
      journal: Evolution
      url: http://onlinelibrary.wiley.com/doi/10.1111/evo.12980/full
    charles2016a:
      year: 2016 
      authors: <b>Mullon, C.</b>, Keller, L., Lehmann, L. 
      title: Evolutionary stability of jointly evolving traits in subdivided populations
      journal: The American Naturalist
      url: http://www.journals.uchicago.edu/doi/abs/10.1086/686900
    charles2015:
      year: 2015
      authors: <b>Mullon, C.</b>, Wright, A., Reuter, M., Pomiankowski, A., Mank, J.
      title: Evolution of dosage compensation under sexual selection differs between X and Z chromosomes
      journal: Nature Communications
      url: https://www.nature.com/articles/ncomms8720
    charles2014:
      year: 2014
      authors: <b>Mullon, C.</b> & Lehmann, L.
      title: The robustness of the weak selection approximation for the evolution of altruism against strong selection
      journal: Journal of Evolutionary Biology
      url: http://onlinelibrary.wiley.com/doi/10.1111/jeb.12462/full
    charles2014:
      year: 2014
      authors: <b>Mullon, C.</b>, Reuter, M., Lehmann, L. 
      title: The evolution and consequences of sex-specific reproductive variance
      journal: Genetics
      url: http://www.genetics.org/content/196/1/235.short
    charles2012b:
      year: 2012 
      authors: <b>Mullon, C.</b>, Pomiankowski, A., Reuter, M.
      title: The effects of selection and genetic drift on the genomic distribution of sexually antagonistic alleles
      journal: Evolution
      url: http://onlinelibrary.wiley.com/doi/10.1111/j.1558-5646.2012.01728.x/full
    charles2012a:
      year: 2012
      authors: <b>Mullon, C.</b>, Pomiankowski, A., Reuter, M. 
      title: Molecular evolution of Drosophila Sex-lethal and related sex determining genes
      journal: BMC Evolutionary biology
      url: https://bmcevolbiol.biomedcentral.com/articles/10.1186/1471-2148-12-5


collections:
  projects:
    output: true
    title: List of Projects
    directory: ./_projects

pagination: 10

# Syntax
markdown: kramdown
highlighter: rouge

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
